# Generated by Django 5.0.6 on 2026-09-15 15:33

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('label', models.CharField(blank=True, default='', help_text='Prénom / rôle', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Chat équipe (alertes)',
                'verbose_name_plural': 'Chats équipe (alertes)',
            },
        ),
        migrations.CreateModel(
            name='Bookmaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Clé technique, ex. 1xbet', max_length=32, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('min_deposit', models.DecimalField(decimal_places=0, default=Decimal('500'), max_digits=12)),
                ('min_payout', models.DecimalField(decimal_places=0, default=Decimal('1000'), max_digits=12)),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage dans le bot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, default='', max_length=64)),
                ('last_name', models.CharField(blank=True, default='', max_length=64)),
                ('phone', models.CharField(blank=True, default='', max_length=32, verbose_name='Dernier numéro mobile money')),
                ('is_blocked', models.BooleanField(default=False, help_text='Un client bloqué ne peut plus rien demander.')),
                ('note', models.TextField(blank=True, default='', help_text="Note interne de l'équipe.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(default='Zagada Service', max_length=64, verbose_name='Nom de la marque')),
                ('deposit_enabled', models.BooleanField(default=True, verbose_name='Dépôts ouverts')),
                ('payout_enabled', models.BooleanField(default=True, verbose_name='Retraits ouverts')),
                ('flooz_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Numéro Flooz (réception des dépôts)')),
                ('tmoney_number', models.CharField(blank=True, default='', max_length=32, verbose_name='Numéro Mixx by Yas / T-Money (réception des dépôts)')),
                ('flooz_account_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Nom du compte Flooz')),
                ('tmoney_account_name', models.CharField(blank=True, default='', max_length=64, verbose_name='Nom du compte Mixx')),
                ('payment_instructions', models.TextField(blank=True, default='', help_text='Affichée sous le numéro marchand (ex. « Mettez votre ID joueur en motif »).', verbose_name='Consigne supplémentaire après le dépôt')),
                ('support_whatsapp', models.CharField(blank=True, default='', help_text='Format international sans espaces, ex. +22890000000.', max_length=32, verbose_name='WhatsApp support')),
                ('support_telegram', models.CharField(blank=True, default='', help_text="Nom d'utilisateur sans @.", max_length=64, verbose_name='Telegram support')),
                ('welcome_text', models.TextField(blank=True, default='Dépôts et retraits rapides chez vos bookmakers, par Flooz et Mixx by Yas.', verbose_name="Texte d'accueil")),
                ('closed_message', models.CharField(default='Ce service est momentanément indisponible. Réessayez plus tard.', max_length=200, verbose_name='Message quand une fonction est fermée')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages',
                'verbose_name_plural': 'Réglages',
            },
        ),
        migrations.CreateModel(
            name='PlayerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.CharField(max_length=64)),
                ('player_name', models.CharField(blank=True, default='', max_length=128)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.bookmaker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='core.client')),
            ],
            options={
                'ordering': ('-last_used_at',),
                'unique_together': {('client', 'bookmaker', 'player_id')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Dépôt'), ('payout', 'Retrait')], max_length=16)),
                ('status', models.CharField(choices=[('awaiting_payment', 'En attente du paiement client'), ('pending', 'À traiter'), ('success', 'Réussie'), ('rejected', 'Rejetée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('player_id', models.CharField(max_length=64, verbose_name='ID joueur')),
                ('player_name', models.CharField(blank=True, default='', max_length=128)),
                ('amount', models.DecimalField(decimal_places=0, default=0, help_text="Montant en FCFA. Pour un retrait : rempli par l'équipe si inconnu.", max_digits=12)),
                ('payout_code', models.CharField(blank=True, default='', max_length=64, verbose_name='Code de retrait')),
                ('network', models.CharField(choices=[('FLOOZ', 'Flooz'), ('TMONEY', 'Mixx by Yas (T-Money)')], max_length=16)),
                ('phone', models.CharField(max_length=32, verbose_name='Numéro mobile money du client')),
                ('payment_reference', models.CharField(blank=True, default='', help_text='ID de transaction Flooz/Mixx fourni par le client (dépôt).', max_length=64, verbose_name='Référence du transfert')),
                ('admin_note', models.CharField(blank=True, default='', help_text='Motif de rejet ou remarque interne.', max_length=255)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bookmaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.bookmaker')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='core.client')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='core_transa_status_288ab7_idx'), models.Index(fields=['kind', 'status'], name='core_transa_kind_e8d68d_idx')],
            },
        ),
    ]
