# Generated by Django 5.0.6 on 2026-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(db_index=True, unique=True)),
                ('step', models.CharField(choices=[('idle', 'Au repos'), ('dep_bookmaker', 'Dépôt — bookmaker'), ('dep_player', 'Dépôt — ID joueur'), ('dep_amount', 'Dépôt — montant'), ('dep_network', 'Dépôt — réseau'), ('dep_phone', 'Dépôt — numéro'), ('dep_confirm', 'Dépôt — confirmation'), ('dep_reference', 'Dépôt — référence du paiement'), ('pay_bookmaker', 'Retrait — bookmaker'), ('pay_player', 'Retrait — ID joueur'), ('pay_code', 'Retrait — code'), ('pay_network', 'Retrait — réseau'), ('pay_phone', 'Retrait — numéro'), ('pay_confirm', 'Retrait — confirmation')], default='idle', max_length=32)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
